import { Button } from "@/components/button"
import Link from "next/link"
import { Metadata } from "next"
import { Faqs } from "@/components/faqs"
import { Authors } from "@/components/authors"
import { Newsletter } from "@/components/newsletter"
import { Footer } from "@/components/shared/footer"

export const metadata: Metadata = {
  title: "The Next.js Ecosystem Overview in One Place",
  description:
    "In-depth content, tools, courses, jobs, and more are curated for you",
}

const ExcludedContent = [
  "Content generated by AI",
  "Long-winded, detailed tutorials",
  "Promotional product tutorials",
  "Content created for SEO, based on keyword analysis",
  "Most UI libraries & npm packages",
  "Listicles, 101's",
]

const InfoAboutContent = () => (
  <div className="py-20 mx-auto w-fit px-2">
    <h2 className="font-bold text-xl sm:text-2xl md:text-3xl text-center mb-4">
      What you won{"'"}t find here
    </h2>
    <ul className="space-y-4 mx-auto w-fit dark:text-zinc-400">
      {ExcludedContent.map((s) => (
        <li key={s} className="text-center">
          {s}
        </li>
      ))}
    </ul>
  </div>
)
export default async function HomePage() {
  return (
    <main className="min-h-screen">
      <div className="min-h-[90vh] flex-col-center pt-10 sm:pt-16 md:pt-24">
        <div className="flex flex-col justify-center text-center animate-in px-2">
          <h1 className="h1 mb-4 text-3xl font-extrabold md:text-4xl lg:text-5xl tracking-tight text-center max-w-3xl mx-auto text-pretty">
            {metadata.title as string}
          </h1>
          <span className="text-lg text-center max-w-2xl mx-auto font-medium px-1 dark:text-zinc-400 border rounded-sm border-dashed">
            Awesome Nextjs Alternative
          </span>
          <p className="text-lg md:text-xl text-center max-w-xl mx-auto dark:text-zinc-500 font-medium pt-3 mb-4 text-pretty">
            {metadata.description}
          </p>
          <Button
            asChild
            className="mt-4 max-w-[12rem] font-semibold w-full mx-auto text-lg"
          >
            <Link href="/docs/latest">Discover</Link>
          </Button>
        </div>
      </div>
      <InfoAboutContent />
      <Newsletter />
      <Authors />
      <Faqs />
      <p className="py-4 text-center dark:text-zinc-500">
        This site is not endorsed by or affiliated with Vercel.
      </p>
      <Footer />
    </main>
  )
}
